### ISSUE TITLE
support for firefox

### ISSUE THREAD

**Issue by ubless607** [lebr0nli/slader-extension#1]
Is there any way I can install for firefox?

**Comment by lebr0nli** [comment]
I update the usage of firefox on readme
But I can't find a good solution to install it on firefox since firefox policy :(
Still hope this solution can help you...

**Comment by ubless607** [comment]
I am having difficulty with your solution because I'm using Firefox for Android.
Is there any way I can change your addon into userscript so that I can install on Tampermonkey?

**Comment by lebr0nli** [comment]
I'm sorry about that...
I think there is no way to work on Tampermonkey since Tampermonkey can't modify request header before a new page loaded.
But I not very sure about that...
Does Tampermonkey support this feature know?
If it doesn't, my extension can't work.
