### ISSUE TITLE
Quizlet answer won't appear

### ISSUE THREAD

**Issue by leduy99** [lebr0nli/slader-extension#13]
Lately, when I used this extension to access quizlet, it showed me this:
![image](https://user-images.githubusercontent.com/37320876/126907112-1687f392-fd76-4944-b5fc-3a6d52007a91.png)
And when I went to chrome to check out what was the problem, I got this:
![image](https://user-images.githubusercontent.com/37320876/126907066-03cc04c7-a0ec-4038-b2eb-1872175587cd.png)
So can anyone tell me how to fix this?

**Comment by EthanHarv** [comment]
Extension is currently broken, use the method I outline in #12

**Comment by Bluebuds0449** [comment]
https://youtu.be/m23Q_datSVM :- use this link and see the video to get for free
