### ISSUE TITLE
Does it work for Mac?

### ISSUE THREAD

**Issue by alvaromartin990** [lebr0nli/slader-extension#3]
Thank you so much for your time to develop this and share it with the community!

I was trying to use it on my Mac, but when I try to add the extension to chrome it does not work, and this is the error.

Thanks

<img width="498" alt="Screen Shot 2021-03-18 at 5 52 18 PM" src="https://user-images.githubusercontent.com/72478214/111707844-ce7cb400-8812-11eb-8ed9-c43cabf047eb.png">

**Comment by lebr0nli** [comment]
Hi,
This extension also works on mac.
Please check out the readme.
Maybe you should try load extension from folder : `~/Documents/Github/slader-extension/slader-limit-bypass` instead of `~/Documents/Github/slader-extension` :)

**Comment by alvaromartin990** [comment]
> Hi,
> This extension also works on mac.
> Please check out the readme.
> Maybe you should try load extension from folder : `~/Documents/Github/slader-extension/slader-limit-bypass` instead of `~/Documents/Github/slader-extension` :)

Sorry for my late reply! It works! Thank you so much!
