### ISSUE TITLE
I'm trying to understand this code

### ISSUE THREAD

**Issue by JHJP** [lebr0nli/slader-extension#4]
Hi, I'm from South Korea and major in computer science.
First of all, thank you for making such a useful extension.

Here is my question about this extension.
Why the x-forwarded-for is need in the code block?

I mean, I know that xff can identify the original user IP. But I think this function is unrelated to delete the paywall.

I have understood other things, not 100%, though. Such as deleting modified headers code block.
It will be helpful for me to understand this code to create another extension by myself.

I'm so so curious to know the reason. 

thank you for reading my question.

**Comment by lebr0nli** [comment]
That's because I removed the paywall's html element.
Check this : https://github.com/lebr0nli/slader-extension/blob/main/slader-limit-bypass/js/content_script.js

**Comment by JHJP** [comment]
thanks alot
