### ISSUE TITLE
Extension no longer works

### ISSUE THREAD

**Issue by ulises-c** [lebr0nli/slader-extension#5]
Slader pushed an update that renders the website useless with this extension.
https://d2nchlq0f2u6vy.cloudfront.net/images/tech_diff.png

**Comment by lebr0nli** [comment]
That's weird, extension still work on my Chrome.
Can you provide more information?

**Comment by ulises-c** [comment]
> 
> 
> That's weird, extension still work on my Chrome.
> Can you provide more information?

I'm using firefox 87.0 on windows 10. Extension was working fine up until this week.

**Comment by ulises-c** [comment]
Same thing happened again. Fixed again by disabling then re-enabling the add-on. Very strange.
